apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-entity
  labels:
    app: api-entity
spec:
  template:
    metadata:
      name: api-entity
      labels:
        app: api-entity
    spec:
      containers:
        - name: api-entity-container
          image: 905418419045.dkr.ecr.us-east-1.amazonaws.com/lanchonete-55/api-entity:main
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: api-entity-secrets
  replicas: 1
  selector:
    matchLabels:
      app: api-entity
