apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-api-entity
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mongodb/data
